/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hanas
 */
public class JF_Modifyitem extends javax.swing.JFrame {
    
    String AdminUsername;
    Connection con;
    Statement st;
    ResultSet rs;
    int tableClickID;
    /**
     * Creates new form JF_Additem
     */
    public JF_Modifyitem() {
        initComponents();
        fillTable();
    }

    public JF_Modifyitem(String username) {
       initComponents();
       AdminUsername=username;
       fillTable();
    }
    private void fillTable(){
        try{
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/OnlineRestaurant","groupone","groupone");
            st=con.createStatement();
            rs=st.executeQuery("Select * from Items");
            itemsTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//end fillTable
    public void closeDB(){
        try{
            rs.close();
            st.close();
            con.close();
        }
        catch(SQLException sqlException){
            sqlException.printStackTrace();
        }
    }//end closeDB
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ItemName = new javax.swing.JTextField();
        ItemPrice = new javax.swing.JTextField();
        jRadioButtonMainDish = new javax.swing.JRadioButton();
        jRadioButtonSweets = new javax.swing.JRadioButton();
        jRadioButtonDrinks = new javax.swing.JRadioButton();
        AddButton = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1090, 740));
        setResizable(false);
        setSize(new java.awt.Dimension(1090, 740));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 500, 48, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 540, 46, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Category");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 500, 67, 22);
        getContentPane().add(ItemName);
        ItemName.setBounds(160, 500, 154, 26);
        getContentPane().add(ItemPrice);
        ItemPrice.setBounds(160, 550, 154, 26);

        buttonGroup1.add(jRadioButtonMainDish);
        jRadioButtonMainDish.setText("Main Dish");
        jRadioButtonMainDish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMainDishActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonMainDish);
        jRadioButtonMainDish.setBounds(470, 500, 101, 29);

        buttonGroup1.add(jRadioButtonSweets);
        jRadioButtonSweets.setText("Sweets");
        jRadioButtonSweets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSweetsActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonSweets);
        jRadioButtonSweets.setBounds(470, 540, 81, 29);

        buttonGroup1.add(jRadioButtonDrinks);
        jRadioButtonDrinks.setText("Drinks");
        getContentPane().add(jRadioButtonDrinks);
        jRadioButtonDrinks.setBounds(470, 580, 77, 29);

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton);
        AddButton.setBounds(160, 440, 90, 29);

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update);
        Update.setBounds(280, 440, 90, 29);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(410, 440, 90, 29);

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Name", "Category", "Price", "Added By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        itemsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(itemsTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 140, 560, 270);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel7.setText("Items Details");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 30, 310, 80);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(810, 630, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/admin.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, -10, 1050, 620);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f1f0de.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 390, 220);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f1f0de.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 200, 200, 240);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f1f0de.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 390, 400, 240);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f1f0de.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 600, 530, 120);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f1f0de.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 590, 490, 110);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/f1f0de.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(930, 560, 160, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMainDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMainDishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMainDishActionPerformed

    private void jRadioButtonSweetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSweetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSweetsActionPerformed

    private void itemsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemsTableMouseClicked
        // TODO add your handling code here:
                try{
            int row=itemsTable.getSelectedRow();
             tableClickID=Integer.parseInt(itemsTable.getModel().getValueAt(row,0).toString());
            //name,categoty,price
            String tableClickName=itemsTable.getModel().getValueAt(row,1).toString();
            double tableClickPrice=Double.parseDouble(itemsTable.getModel().getValueAt(row,3).toString());
            String tableClickCategory=itemsTable.getModel().getValueAt(row,2).toString();
            
//            txtID.setText(""+tableClickID);
            ItemName.setText(tableClickName);
            ItemPrice.setText(""+tableClickPrice);
            if(tableClickCategory.equals("MainDish"))
            {
                jRadioButtonMainDish.setSelected(true);
            }
            else if (tableClickCategory.equals("Drink"))
            {
                jRadioButtonDrinks.setSelected(true);
            }
            else
                jRadioButtonSweets.setSelected(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    //end mouseClicked

    }//GEN-LAST:event_itemsTableMouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        try{
            PreparedStatement insertSt=con.prepareStatement("INSERT INTO Items (NAME,CATEGORY,PRICE,ADDEDBY) VALUES (?,?,?,?)");
            insertSt.setString(1,ItemName.getText());
            insertSt.setDouble(3,Double.valueOf(ItemPrice.getText()));
            insertSt.setString(4,AdminUsername);
            if(jRadioButtonDrinks.isSelected())
            {
                insertSt.setString(2,"Drink");
            }
            else if(jRadioButtonMainDish.isSelected())
            {
                insertSt.setString(2,"MainDish");
            }
            else if(jRadioButtonSweets.isSelected())
            {
                insertSt.setString(2,"Sweet");
            }
            else
            {
                 JOptionPane.showMessageDialog(null, "You need to specify the Category of the item!","Category needed",JOptionPane.WARNING_MESSAGE);
                 
            }
        
            insertSt.executeUpdate();
        
            JOptionPane.showMessageDialog(null, "Item Added");
        
            closeDB();
            fillTable();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Exception: "+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    //end btnAdd

    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
                try{
            int answer=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this item?","Delete Item",JOptionPane.YES_NO_OPTION);
            if(answer==JOptionPane.YES_OPTION){
                  String sql="Delete from Items where ITEMID="+tableClickID;
                int rows=st.executeUpdate(sql);
                if(rows==1){
                    JOptionPane.showMessageDialog(null,"Item Deleted");
                }
                ItemName.setText("");
                ItemPrice.setText("");
                closeDB();
                fillTable();
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
               
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
                try{
            PreparedStatement updateSt=con.prepareStatement("Update Items SET NAME=?,CATEGORY=?,PRICE=? where ITEMID=?");
            updateSt.setString(1,ItemName.getText());
            if(jRadioButtonDrinks.isSelected())
            {
                updateSt.setString(2,"Drink");
            }
            else if(jRadioButtonMainDish.isSelected())
            {
                updateSt.setString(2,"MainDish");
            }
            else if(jRadioButtonSweets.isSelected())
            {
                updateSt.setString(2,"Sweet");
            }
            updateSt.setDouble(3,Double.valueOf(ItemPrice.getText()));
            updateSt.setInt(4,tableClickID);
            
            int updatedRows = updateSt.executeUpdate();
            if(updatedRows > 0){
                JOptionPane.showMessageDialog(null, "Item Updated");
            }
            else{
                JOptionPane.showMessageDialog(null, "Update was not successful.");
            }
            
            closeDB();
            fillTable();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new JF_Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Modifyitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Modifyitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Modifyitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Modifyitem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Modifyitem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField ItemName;
    private javax.swing.JTextField ItemPrice;
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable itemsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDrinks;
    private javax.swing.JRadioButton jRadioButtonMainDish;
    private javax.swing.JRadioButton jRadioButtonSweets;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
