/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import onlinerestaurant.Payments;
import onlinerestaurant.PayCash;
import static MyConnection.CustomerOperation.Paymentsave;
import static MyConnection.CustomerOperation.PaymentCashsave;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Hanas
 */
public class JF_Payments extends javax.swing.JFrame {
    String Price;
    int OrderId;
    /**
     * Creates new form JF_Payments
     */
    public JF_Payments() {
        initComponents();
    }
    public JF_Payments(String price) {
        
        initComponents();
        getCurrentDate();
        PriceLabel2.setText(price);
        priceHiddenLabel.setVisible(false);
        priceHiddenLabel.setText(price);
 
    }
    public JF_Payments(int orderID,double sum)
    {
        initComponents();
        getCurrentDate();
        OrderId=orderID;
        Price=String.valueOf(sum);
        PriceLabel2.setText(Price);
        priceHiddenLabel.setVisible(false);
        priceHiddenLabel.setText(Price);
        setEditability(false);
    }

    private void setEditability(Boolean b)
    {
        CardNText.setEditable(b);
        jPasswordField1.setEditable(b);
        NameText.setEditable(b);
    }
    private void getCurrentDate(){
        try{
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            //Get the current date
            Calendar c = Calendar.getInstance();
            //set the current date
            PayDateLabel2.setText(sdf.format(c.getTime()));
            }catch( Exception e)
            {
            
            }
    }
    private double calculateDiscount(Double price){
       Double discount = (price*10)/100;
    
       return price - discount;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaymentLabel = new javax.swing.JLabel();
        PaymentMethodLabel = new javax.swing.JLabel();
        CardNumLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        PriceLabel2 = new javax.swing.JLabel();
        PayDateLabel = new javax.swing.JLabel();
        PayDateLabel2 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        PaymentComboBox = new javax.swing.JComboBox<>();
        CardNText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        CCVLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        priceHiddenLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 670));
        setSize(new java.awt.Dimension(840, 670));
        getContentPane().setLayout(null);

        PaymentLabel.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        PaymentLabel.setText("Payment");
        getContentPane().add(PaymentLabel);
        PaymentLabel.setBounds(260, 20, 150, 50);

        PaymentMethodLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PaymentMethodLabel.setText("Payment Method:");
        getContentPane().add(PaymentMethodLabel);
        PaymentMethodLabel.setBounds(200, 120, 139, 20);

        CardNumLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CardNumLabel.setText("Card Number:");
        getContentPane().add(CardNumLabel);
        CardNumLabel.setBounds(220, 170, 120, 22);

        NameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NameLabel.setText("Name On Card:");
        getContentPane().add(NameLabel);
        NameLabel.setBounds(210, 220, 130, 31);

        PriceLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        PriceLabel.setText("Total Price:");
        getContentPane().add(PriceLabel);
        PriceLabel.setBounds(230, 270, 100, 20);

        PriceLabel2.setFont(new java.awt.Font("Palatino", 2, 18)); // NOI18N
        PriceLabel2.setText("total price");
        getContentPane().add(PriceLabel2);
        PriceLabel2.setBounds(410, 270, 142, 42);

        PayDateLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        PayDateLabel.setText("Payment Date:");
        getContentPane().add(PayDateLabel);
        PayDateLabel.setBounds(220, 320, 120, 20);

        PayDateLabel2.setFont(new java.awt.Font("Palatino", 2, 18)); // NOI18N
        PayDateLabel2.setText("date");
        getContentPane().add(PayDateLabel2);
        PayDateLabel2.setBounds(420, 320, 150, 24);

        BackButton.setFont(new java.awt.Font("Palatino", 1, 14)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(567, 310, 90, 41);

        ConfirmButton.setFont(new java.awt.Font("Palatino", 1, 14)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmButton);
        ConfirmButton.setBounds(690, 310, 110, 41);

        PaymentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit Card", " " }));
        PaymentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(PaymentComboBox);
        PaymentComboBox.setBounds(390, 110, 160, 42);

        CardNText.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        CardNText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNTextActionPerformed(evt);
            }
        });
        getContentPane().add(CardNText);
        CardNText.setBounds(350, 160, 300, 40);

        NameText.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });
        getContentPane().add(NameText);
        NameText.setBounds(370, 210, 170, 40);

        CCVLabel.setFont(new java.awt.Font("Palatino", 0, 18)); // NOI18N
        CCVLabel.setText("CCV:");
        getContentPane().add(CCVLabel);
        CCVLabel.setBounds(600, 220, 50, 20);

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(690, 210, 70, 40);
        getContentPane().add(priceHiddenLabel);
        priceHiddenLabel.setBounds(430, 520, 0, 0);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/payment.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 270, 830, 450);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/White.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -60, 850, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PaymentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentComboBoxActionPerformed
        // TODO add your handling code here:
                if(PaymentComboBox.getSelectedItem().toString().equals("Credit Card")){ 
                //set fileds to be editable
                setEditability(true);
                Double price =calculateDiscount(Double.parseDouble(PriceLabel2.getText()));
                PriceLabel2.setText(price.toString()); 
            }else if(PaymentComboBox.getSelectedItem().toString().equals("Cash")){
                //set fileds to be non editable
                setEditability(false);
                PriceLabel2.setText(priceHiddenLabel.getText());
            
        }

    }//GEN-LAST:event_PaymentComboBoxActionPerformed

    private void CardNTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNTextActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CardNTextActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        // TODO add your handling code here:
                String CardNumber=CardNText.getText();
                int DigitNum=CardNumber.length();
                String CCVNumber=jPasswordField1.getText();
                int CCVNum=CCVNumber.length();
        if(PaymentComboBox.getSelectedItem().toString().equals("Credit Card")&&(DigitNum!=9||CCVNum!=3))
            {
                if(DigitNum!=9||CCVNum!=3)
                {
                    if(DigitNum!=9)
                    JOptionPane.showMessageDialog(null,"Card Number Should contain 9 Digits only!");
                    if(CCVNum!=3)
                    JOptionPane.showMessageDialog(null,"CCV Number Should contain 3 Digits only!");
                }
            }
        
        else
        {
        String paymentType, cardNumber,  cardName, paymentDate,ccv;
           double amountToBePaid;  
           int CCV;
           paymentDate=PayDateLabel2.getText();
           amountToBePaid=Double.parseDouble(PriceLabel2.getText());
            if(PaymentComboBox.getSelectedItem().toString().equals("Credit Card")){ 
                paymentType=PaymentComboBox.getSelectedItem().toString();
                cardNumber=CardNText.getText();
                cardName=NameText.getText();
                ccv=jPasswordField1.getText();
                CCV=Integer.parseInt(ccv);
                Payments payment=new Payments(paymentType, cardNumber,  cardName, CCV, paymentDate,amountToBePaid);
                Paymentsave(payment,OrderId);
           }
           if(PaymentComboBox.getSelectedItem().toString().equals("Cash")){ 
               
                PayCash payCash= new PayCash(amountToBePaid,paymentDate);
                PaymentCashsave(payCash,OrderId);
            }
           
           setVisible(false);
           new JF_Bill(OrderId).setVisible(true);
        }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new JF_Cart(OrderId).setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CCVLabel;
    private javax.swing.JTextField CardNText;
    private javax.swing.JLabel CardNumLabel;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameText;
    private javax.swing.JLabel PayDateLabel;
    private javax.swing.JLabel PayDateLabel2;
    private javax.swing.JComboBox<String> PaymentComboBox;
    private javax.swing.JLabel PaymentLabel;
    private javax.swing.JLabel PaymentMethodLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel PriceLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel priceHiddenLabel;
    // End of variables declaration//GEN-END:variables
}
