/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import static MyConnection.CustomerOperation.login;
import static MyConnection.CustomerOperation.save;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import onlinerestaurant.CustomerSighUp;
import onlinerestaurant.Users;

/**
 *
 * @author Hanas
 */
public class JF_SighUp extends javax.swing.JFrame {
    boolean sign_up_flag=true;
    CustomerSighUp user;
    /**
     * Creates new form JF_SighUp
     */
    public JF_SighUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FnameText = new javax.swing.JTextField();
        LnameText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CityCombo = new javax.swing.JComboBox<>();
        NeighborhoodCombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        PasswordText = new javax.swing.JPasswordField();
        NextButton = new javax.swing.JButton();
        jButton1Exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        setPreferredSize(new java.awt.Dimension(950, 860));
        setSize(new java.awt.Dimension(950, 860));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText(" Sign Up");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 10, 150, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("------------Contact Information---------------");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 450, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("First Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 130, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 180, 130, 29);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 210, 90, 40);

        FnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameTextActionPerformed(evt);
            }
        });
        getContentPane().add(FnameText);
        FnameText.setBounds(150, 140, 167, 22);
        getContentPane().add(LnameText);
        LnameText.setBounds(150, 180, 167, 22);
        getContentPane().add(EmailText);
        EmailText.setBounds(150, 220, 167, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("------------Address Information---------------");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 90, 460, 29);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("City");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 140, 90, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("NeighborHood");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(490, 200, 160, 30);

        CityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dammam", "Khobar", "AlAhsa", "Jubail" }));
        CityCombo.setSelectedIndex(-1);
        CityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityComboActionPerformed(evt);
            }
        });
        getContentPane().add(CityCombo);
        CityCombo.setBounds(680, 150, 115, 22);

        getContentPane().add(NeighborhoodCombo);
        NeighborhoodCombo.setBounds(680, 200, 115, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("-------------Account Information--------------");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 280, 450, 29);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Username");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 330, 120, 29);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Password");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 390, 120, 30);
        getContentPane().add(UsernameText);
        UsernameText.setBounds(420, 330, 168, 22);
        getContentPane().add(PasswordText);
        PasswordText.setBounds(420, 390, 169, 22);

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton);
        NextButton.setBounds(560, 460, 78, 28);

        jButton1Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1Exit.setText("Exit");
        jButton1Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Exit);
        jButton1Exit.setBounds(450, 460, 77, 28);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 460, 80, 28);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sUP.gif"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(70, 470, 1010, 350);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/White.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, -20, 1170, 890);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameTextActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        sign_up_flag=true;
        String fname,lname,email,password,username;
        fname=FnameText.getText();
        lname=LnameText.getText();
        email=EmailText.getText();
        username=UsernameText.getText();
        password=PasswordText.getText();
       
        String City,neighbor;
        try{
        City=CityCombo.getSelectedItem().toString();
        neighbor=NeighborhoodCombo.getSelectedItem().toString();
        }
        catch(NullPointerException e)
        {
            City="Not Defined";
            neighbor="Not Defined";
        }
        CustomerSighUp user=new CustomerSighUp(fname,lname,email,City,neighbor,username,password);
        ArrayList<String> wrong = new ArrayList<>();

        if (fname.equals("")) {
            wrong.add("Frist Name is Empty");
            sign_up_flag = false;
        }
       
        if (lname.equals("")) {
            wrong.add("Last Name is Empty");
            sign_up_flag = false;
        }

        if (email.equals("")) {
            wrong.add("Email is Empty");
            sign_up_flag = false;
        } else 
        {
            if ((email.contains("@")) && (email.endsWith(".com") || email.endsWith(".sa")))
            {
            } 
            else 
                    {
                     wrong.add("Wrong formatted email");
                     sign_up_flag = false;
                     }
        }
        int m=login(username,password);
        if (username.equals("")) {
            wrong.add("username is Empty");
            sign_up_flag = false;
        }else{
            if( m == 1){
                  wrong.add("Customer already exist! please log in");
                  sign_up_flag = false;
            }
        }
        if (password.equals("")) {
            wrong.add("password is Empty");
            sign_up_flag = false;
        }
        if (sign_up_flag) {
              save(user);  
              setVisible(false);
              new JF_menu(username).setVisible(true);
                
        } 
            else {
            String str = "Please fix the following:";
            for (int i = 0; i < wrong.size(); i++) {
                str += ("\n" + (1 + i) + " ." + wrong.get(i));
            }
            JOptionPane.showMessageDialog(this, str, "warning", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_NextButtonActionPerformed

    private void jButton1ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ExitActionPerformed
        // TODO add your handling code here:
         int a= JOptionPane.showConfirmDialog(null, "Do you really want to close the Application? ","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            setVisible(false);
            new JF_Login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityComboActionPerformed
        // TODO add your handling code here:

        if(CityCombo.getSelectedItem().toString().equals("Dammam"))
        {
            NeighborhoodCombo.removeAllItems();
            NeighborhoodCombo.addItem("AlNuzhah");
            NeighborhoodCombo.addItem("AlWahah");
            NeighborhoodCombo.addItem("AlRayan");
        }
        else if(CityCombo.getSelectedItem().toString().equals("Khobar"))
                {
                    NeighborhoodCombo.removeAllItems();
                    NeighborhoodCombo.addItem("Alyarmouk");
                    NeighborhoodCombo.addItem("Alrawabi");
                    NeighborhoodCombo.addItem("Alolaya");
                }
        else if(CityCombo.getSelectedItem().toString().equals("Jubail"))
        {
                    NeighborhoodCombo.removeAllItems();
                    NeighborhoodCombo.addItem("AlFateh");
                    NeighborhoodCombo.addItem("AlSalmaniya");
                    NeighborhoodCombo.addItem("AlSeef");
        }
        else
        {
                    NeighborhoodCombo.removeAllItems();
                    NeighborhoodCombo.addItem("AlAndalus");
                    NeighborhoodCombo.addItem("AlQadisiyah");
        }
    }//GEN-LAST:event_CityComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_SighUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_SighUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_SighUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_SighUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_SighUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CityCombo;
    private javax.swing.JTextField EmailText;
    private javax.swing.JTextField FnameText;
    private javax.swing.JTextField LnameText;
    private javax.swing.JComboBox<String> NeighborhoodCombo;
    private javax.swing.JButton NextButton;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
